### ISSUE TITLE
A small bug in branch "PM_Rotor"

### ISSUE THREAD

**Issue by horychen** [Severson-Group/eMach-matlab#104]
In the file below, at Line 112, arc should be arc_c. 
> model_obj\crosssects\innerNotchedRotor\CrossSectInnerNotchedRotor.m

Also refer to the figure below.
![image](https://user-images.githubusercontent.com/44207479/59409683-6d41ca00-8d7c-11e9-9670-70f3c53d428f.png)

**Comment by ngadiyar93** [comment]
@horychen  I have corrected it now. Thanks for letting me know.
