### ISSUE TITLE
Update Location2D class

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/eMach-matlab#11]
Currently, Location2D has two properties for its rotation field. There should only be one as this defines the 2D rotation of the cross section in the xy plane. Please update Location2D class to reflect this. Consider adding simple PDF diagram of how this class is used (see below), as well as updating the class comments to give a good description.

![img_20190220_102854](https://user-images.githubusercontent.com/20168990/53133747-dc7b8000-3539-11e9-9191-23a2795e9501.jpg)

Also, please implement Location2D method for transforming coordinates according to class properties, e.g., `[new_x, new_y] = Location2D.transform([x,y])`. Then, use this method in the arc and trapezoid cross sections for drawing. Update examples to show this new ability works.

Create a topic branch for this work based off of `develop`. Branch `develop` has Nathan's new architecture implementation changes. Once done, create a PR for review.

**Comment by elsevers** [comment]
Looks like this is completed in PR #19
