### ISSUE TITLE
Identify best practices for structuring a Python code base

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#110]
Identify best practices and guidelines for the following items:

- [ ] How much content should reside in a file? 
- [ ] When to break files out into separate folders? 
- [ ] Does it ever make sense to create python functions that are not a part of a class?
- [ ] What aspects of the Python programming language should we be aware of for implementing SOLIDD?
- [ ] Take a look at how we have currently structured the files in eMach in MATLAB. Is that a logical approach for how to do it Python? Can porting the code over be as straight forward as just making Python versions of each matlab file?
- [ ] Are there special considerations that most be taken into account if we want to publish this through a distribution like Conda?

Keep this simple and introductory -- most know very little Python!

**Comment by jlebesnerais** [comment]
Hi Eric,
I am following a bit your project and I think there might be some synergies of development with Pyleecan project (https://github.com/Eomys/pyleecan) especially if you are thinking working with Python. Pyleecan is currently fully coupled to FEMM but it also aims at being easily coupled to electromagnetic commercial software, we have experienced coupling with Flux and we would be happy to help you coupling it to Magnet. 
You can contact us at pyleecan@framalistes.org to arrange a conference call and join our development efforts.
Regards,
Jean

**Comment by elsevers** [comment]
[PR#110_PythonBestPractice_15-10-2020_update.docx](https://github.com/Severson-Group/eMach/files/5391770/PR.110_PythonBestPractice_15-10-2020_update.docx)

@aimthiazz sent me these notes, to which I am responding:

Thanks @Imthiaz. This looks like a good start. I would like you to expand it more toward practical, introductory aspects in our discussion today. I want people to walk away from this and be able to immediately start using it as they code in python. To this end, I would prioritize the discussion order like this:

**High priority**: `How much content should reside in a file?` -- with subquestions of:
1. `When to break files out into separate folders?` 
2. `Does it ever make sense to create python functions that are not a part of a class?`
3. Can you give us practical guidelines on file content that are specific to Python? Should multiple classes ever be in the same file? Should one file hold both classes and functions that are not part of that class?

**Medium priority**: `What aspects of the Python programming language should we be aware of for implementing SOLIDD?`

**Medium priority**: `Take a look at how we have currently structured the files in eMach in MATLAB. Is that a logical approach for how to do it Python? Can porting the code over be as straight forward as just making Python versions of each matlab file?` (Or do we need to rethink the structure? If we can have a nearly identical structure, that makes life easy! I had envisioned that we have a `python` subfolder that just recreates the exact same folder structure as is currently in `eMach` for MATLAB)

**Low priority** _this can be postponed to a future discussion if needed_: `Are there special considerations that most be taken into account if we want to publish this through a distribution like Conda?`

**Comment by elsevers** [comment]
@aimthiazz Please "complete" this issue by attaching reference material to the issue that addresses each of these questions. This can be your slides.

**Comment by aimthiazz** [comment]
Please find the Slides attached. 
[Identify best practices for structuring python code #110.pdf](https://github.com/Severson-Group/eMach/files/5414566/Identify.best.practices.for.structuring.python.code.110.pdf)
