### ISSUE TITLE
How to open MagNet from Python

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#111]
Investigate how MagNet is opened from Matlab and determine the best way to open it in Python. Create an example Python script that does the following:

1. Opens MagNet 
2. Draws a circle of radius `50mm`
3. Draws a square inside the circle with a side length of `30mm`

Attach the example script to this issue.

**Comment by Bharat-Ramadas** [comment]
[CircleSquare_MagNet.zip](https://github.com/Severson-Group/eMach/files/5283348/CircleSquare_MagNet.zip)
@elsevers Please find below the python script for this 'issue'

from win32com.client import DispatchEx  #module needed for opening MagNet

MN = DispatchEx("MagNet.Application")   #open MagNet
MN.Visible = True                       #make the MagNet window visible

#Get Handles to MAGNET Scripting Interfaces
Doc = MN.newDocument()                  
View = Doc.getView()

#define function for drawing circles x,y are the coordinates of the centre, r is radius
def DrawCircle(x, y, r):
    View.newCircle(x, y, r)

#define function for drawing sqaures x,y are the coordinates of the centre, l is side length
def DrawSquare(x, y, l):
    View.newLine(x-l/2,y-l/2,x+l/2,y-l/2)
    View.newLine(x+l/2,y-l/2,x+l/2,y+l/2)
    View.newLine(x+l/2,y+l/2,x-l/2,y+l/2)
    View.newLine(x-l/2,y+l/2,x-l/2,y-l/2)

DrawCircle(0, 0, 50)

DrawSquare(0, 0, 30)

    
View.viewAll() #zoom out to view whole geometry

**Comment by elsevers** [comment]
Hello Bharat -- could you attach a `.py` script with this in it? Thanks.

**Comment by elsevers** [comment]
@Bharat-Ramadas, I have two requests:

- [x] Create a PR that adds this script to the `add-python-support` branch inside `python/tools/magnet`
- [x] Provide instructions for how to use this script (I recall that you had to modify your environment path)

**Comment by Bharat-Ramadas** [comment]
Instructions and script have been added along with PR #122
