### ISSUE TITLE
Add examples that use JMAG MATLAB tool

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#126]
Once #125 has been implemented, let's add examples to the eMach code base that use this tool. 

This means two things:
1. Updating the drawing/making examples in the root of `eMach/examples/`  to have a `if` switch to use JMAG instead of TikZ or MagNet

2. Adding support for a complete solve using JMAG to one or more of our FEA examples `eMach/examples/`  (i.e., 
`eMach/examples/exampleAFPM2D/` or the yet to be merged #67) to be able to use either JMAG or MagNet. Doing this may [optionally] involve creating the necessary porcelain/plumbing functions.

**Comment by ngadiyar93** [comment]
We have examples that use JMAG to draw cross-sections.
However, creating porcelain functions and supporting a complete solve isn't implemented yet. This will need a lot more time to implement and should probably be a separate issue?
