### ISSUE TITLE
Implement `makeSolid()` action

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/eMach-matlab#13]
This is still fuzzy to me about how to implement this... We need to iron this out.

---

The following is how the system will work(?) from top level `main.m`:

```MATLAB

% Make cross sections....
cs1 = ___;
cs2 = ___;

% Make components....
comp1 = ___cs1, cs2___;

% Draw component in tool
comp1.make(Tool t)

```

Tasks:
- remove CrossSection.select()
- CrossSection.draw() returns a token as local variable

```MATLAB
Tool.makeSolid(tokensFromDrawingCrossSections) {
  foreach token:
    % Tool specific code here that uses token to "select" the component primitives...
}
```

**Comment by elsevers** [comment]
See pull request #32

**Comment by elsevers** [comment]
Pull request #32 merged. New issue created to apply this to other cross-sections: #47
