### ISSUE TITLE
Add cross section class implementation for new geometries

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/eMach-matlab#17]
If possible, try to make cross section classes that implement the drawings created in #16.

**Comment by elsevers** [comment]
@Anvar-Khamitov @Nick-Hemenway @ngadiyar93: Please post an update on this in the comments.

**Comment by ngadiyar93** [comment]
I had implemented this based on the parameterization that I had up for discussion on Monday. 
However, as we decided to change the parameterization on Monday, I am working on modifying the code to reflect the same. I am unsure if I can complete this today.  May probably take a day more.

This enhancement was moved to a new issue "Fix Rotor Parameterization", due 03/04, on monday. So, probably, this issue can be closed?

**Comment by Anvar-Khamitov** [comment]
The same with me. I may need a day or more.

**Comment by Nick-Hemenway** [comment]
I have not been able to figure out how to add the base fillets to the inner rotor stator yet. As of now, I have two branches; one called "inner_rotor", and one called "add_fillets" which is branched off of "inner_rotor". The inner_rotor branch could be merged but the add_fillets branch is still a work in progress.
