### ISSUE TITLE
Tools should use open and close for files, not the application instance

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#172]
Revise the tools (MagNet and JMAG) so that:

1. `open` and `close` are used to open and close a project/file
2. The application itself is opened when the tool object instance is created (in the constructor)
3. Create a destructor method that is called when the tool object instance is destroyed. This destructor should exit the tool application. See [here](https://www.mathworks.com/help/matlab/matlab_oop/handle-class-destructors.html) for instructions on how to do this in MATLAB.
4. Create an example demonstrating the complete lifecycle of a tool. That is, create a tool object instance (see that the tool application opens), open a file (or create a new file), close the file, and then destroy the object instance and watch the tool application close)

Code to change:
1. The tool class (i.e. `MagNet.m`)
    1. `visible` moves from the `open()` function to the constructor
    2. `mn` moves from the `open()` function to the constructor
2. The `tool` abstract base class (update comments and function signature)

https://github.com/Severson-Group/eMach/blob/f8bd845a7275ece4f4618324923e5ff66876eb77/tools/magnet/MagNet.m#L17-L65

**Comment by ngadiyar93** [comment]
The MagNet MATLAB tool was updated and merged in #186
