### ISSUE TITLE
Move unary operations to DimBase so that they also apply to DimAngular

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#173]
PR #150 added dimensions and created unary operations for linear dimensions. These operations also should apply to angular dimensions. 

Please move the unary operations to the `DimBase` class so that they work for both linear and radial dimensions.

https://github.com/Severson-Group/eMach/blob/beb4fc720a5c1c3abd741eadc791706c0b621e63/python/emach/model_obj/dimensions/dim_linear.py#L12-L61

**Comment by aimthiazz** [comment]
I have moved the unary operations to `DimBase`.
