### ISSUE TITLE
Clean up DimLinear code to remove ambiguous return paths

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#174]
Several functions in the `DimLinear` class have conditional paths that are not complete. For example, see the code below:

https://github.com/Severson-Group/eMach/blob/beb4fc720a5c1c3abd741eadc791706c0b621e63/python/emach/model_obj/dimensions/dim_linear.py#L22-L31

There is no `else` for the last `if`, and so it appears as though it is possible for the program to exit this function without returning a value. This add potential for errors in the code. Please clean up.

Further, I question whether it is necessary to check `isinstance(self, DimLinear)` -- since this code is appearing in the `DimLinear` class, wouldn't `self` always be of type `DimLinear`?

Please clean up these functions:
- [x] `__mul__`
- [x] `__rmul__`
- [x] `__truediv__`
- [x] `__rtruediv__`

**Comment by aimthiazz** [comment]
I agree with your comment on whether is it necessary to check `isinstance(self, DimLinear)` I have modified the code to check for exception, else do normal operation.
