### ISSUE TITLE
Python dimensions should raise exception for squared operation

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#175]
The following code should throw an exception, but it does not:

```python
inchObject = DimInch(1)
inchObject**2
```

Please fix.

**Comment by aimthiazz** [comment]
Addressed this by overloading power operator using `__pow__`. The following power operations will throw an exception
```python
dimensionObject**scalar
scalar**dimensionsObject
dimensionsObject**dimensionsObject
```

Please note that the above-specified power operations are supported in MATLAB (screenshot attached)
![image](https://user-images.githubusercontent.com/14706814/110216172-32969400-7e73-11eb-9adc-d40bf3acedb2.png)
