### ISSUE TITLE
Thoughts while updating class

### ISSUE THREAD

**Issue by Nick-Hemenway** [Severson-Group/eMach-matlab#20]
-should the depth information be stored with the cross section and not at the component level?
-we should always convert angular dimensions to degrees in the backend so the user can construct geometries using any angular dimension on front end without having to remember to convert to radians. (need to remove restriction for values <2pi)

**Comment by elsevers** [comment]
The cross-section shouldn't have to know what it is a cross-section of. That is, it should have no knowledge of how the cross-section is to be used. The depth information should be stored in either the makeSolidBase object or the component. Preferably in the makeSolidBase object.

**Comment by Nick-Hemenway** [comment]
This is what both Nathan and I were thinking but it is currently implemented as being an attribute in the cross section. This will need to be changed.

**Comment by elsevers** [comment]
@Nick-Hemenway, separate this out into two distinct items on our issues list (and then close this issue). Both items should have the tag of `architecture` (if I understand our labeling scheme appropriately).

- depth/revolve information

- angular dimensions

(@npetersen2, are we using the system as intended?)

**Comment by npetersen2** [comment]
Yes, this is what I intended for GitHub issues. If you desire different tags and labels etc, feel free to change it.
