### ISSUE TITLE
Depth/Revolve information

### ISSUE THREAD

**Issue by Nick-Hemenway** [Severson-Group/eMach-matlab#22]
At present, the depth information, is stored as an attribute in the cross section. I propose that this is implemented at the component level

**Comment by elsevers** [comment]
The cross-section shouldn't have to know what it is a cross-section of. That is, it should have no knowledge of how the cross-section is to be used. The depth information should be stored in either the makeSolidBase object or the component. Preferably in the makeSolidBase object.

**Comment by npetersen2** [comment]
See implementation PR #32.

**Comment by elsevers** [comment]
Pull request merged. I am closing this. Re-open if you think more discussion is needed.
