### ISSUE TITLE
Update Location2d to operate on matrices of xy coordinates

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#39]
Follow up to pull request #19:

Change `Location2d.transformCoords(obj, x, y, theta)`: to be `transformCoords(obj, xyCords, addTheta)`, where `xyCords` is a matrix of coordinates (see below) and `addTheta` is as currently defined (and optional). This will allow for compact usage when calling the function.

```
xyCords = [x1, y1 
         x2, y2 
         x3, y3
         x4, y4];
```
Allows for:
`newCords = locObj.transformCoords(obj, [arcStartXY; arcCenterXY; arcEndXY]);`

**Comment by npetersen2** [comment]
Done in PR.
