### ISSUE TITLE
Revise hollow rectangle labeling

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#42]
Revise the `CrossSectHollowRect` class

* Change `l_o` to `w`
* Change `b_o` to `h`
* Change `t_1` through `t_4` numbering. Place `t_1` on right side and go counter-clockwise. That is: `t_2` on the top, `t_3` on left, etc.

(on drawings and in the source code)

**Comment by ngadiyar93** [comment]
I have updated it and Submitted a PR #43
