### ISSUE TITLE
Add additional make operations

### ISSUE THREAD

**Issue by Nick-Hemenway** [Severson-Group/eMach-matlab#56]
-makeRevolve
-makeSweptProfile
-makeExtrude (rename this function from makeSimpleExtrude)

**Comment by npetersen2** [comment]
@elsevers please attach picture you took to this issue.

**Comment by elsevers** [comment]
![IMG_20190304_143017](https://user-images.githubusercontent.com/7421348/54464857-69cf8000-4746-11e9-9b2a-03a545a06d95.jpg)

**Comment by elsevers** [comment]
Implemented in PR #65
