### ISSUE TITLE
Create duplicate method in each cross section

### ISSUE THREAD

**Issue by Nick-Hemenway** [Severson-Group/eMach-matlab#57]
It would be convenient to add a duplicate method to each cross section that would take in a new location object. This would make duplicating components such as permanent magnets really easy. I thought this would work by doing something like:
```
bread1 = CrossSectBreadloaf( ... )
bread2 = bread1
bread2.location = NewLocationObject
```
This does not work however as the attributes cannot be overridden. It would be nice if we could do something like the following:
```
bread1 = CrossSectBreadloaf( ... )
bread2 = bread1.duplicate(NewLocationObject)

```
where "NewLocationObject" is a Location2D object.

**Comment by npetersen2** [comment]
Change method to `cs.moveCopy(NewLocation)`

Moving to backlog

**Comment by elsevers** [comment]
See PR#57
