### ISSUE TITLE
Propose architecture change

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#7]
- Think about injecting a class which implements the drawing functionality.
- Think about components as cross sections.
- Components export line/arc primitives

THOUGHTS:

XFEMM < Tool & Drawer2D & MakeSolid
   - implements abstract methods

Tool
     - open()
     - close()
     - cmd()
     - select()
     - extrude()
     - revolve()

- Drawer2D
    - makeArc()
    - makeLine()
    - select() (this is optional (?))

- Component
    - model() { for all CrossSections: 1. cs.draw(), 2. cs.select()           3. MakeSolid.make() }
    - CrossSection objects []
    - Material obj
    - MakeSolid obj
    - Location3D obj

- CrossSection (compBase)
    - draw()
    - select()
    - Drawer2D _object (just new line, new arc, select result)
    - Dimensions object
    - Location2D object (always in xy plane)

- MakeSolid (?)
    - make() {
         revolve() / extrude()
      }

**Comment by elsevers** [comment]
main()

// Make CrossSections
CrossSection cs1;

// Assemble into Component
Component stator(MakeExtrusion, ......);
c.add(cs1);

stator.model();
// TODO: change model name to "make()"

**Comment by npetersen2** [comment]
This issue served as idea space for new architecture. As this has been implemented in PR #8, I am closing this issue. Will open new issues for bugs and new ideas.
