### ISSUE TITLE
Create a new PR for operator overloading

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#71]
See @elsevers review comments for your new PR.

Old PR was #53

**Comment by ngadiyar93** [comment]
Add unit test and lhs/rhs changes to `mtimes` function. Also, continue to implement other overload functions.

**Comment by ngadiyar93** [comment]
`makeSolidExample` seems to not be working without `rhs` abilities... Please fix ASAP to fix `makeSolidExample`.

**Comment by npetersen2** [comment]
Done
