### ISSUE TITLE
The example in "exampleHollowRect.m" is not working

### ISSUE THREAD

**Issue by horychen** [Severson-Group/eMach-matlab#91]
The branch is "develop".

**It has to do with the plus operation between DimLinear and double.**

> Error using  +  (line 11)
> Expected input to be one of these types:
> 
> DimLinear
> 
> Instead its type was double.

A print-screen is attached:
![image](https://user-images.githubusercontent.com/44207479/55507246-d7bbe880-561c-11e9-915c-d12533c7e3e6.png)

**Comment by npetersen2** [comment]
My code in PR to clean up repo should fix this. Have you pulled from develop since the meeting?
