### ISSUE TITLE
Rewrite XFEMM tests to be formal unit tests

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#96]
Refractor the PR #86 to use the Matlab unit test framework. See @npetersen2's examples. 

- Move unit tests to the `tests` folder. 
- Use `assert` command in Matlab
- Use naming convention: the first word of each file with an XFEMM test should be `xfemm` and the last word should be `Tests`. Example name: `xfemmRemoveExtraNodesTest.m`
- Each test should have a Word (or preferably a Markdown) file of the same name and in the same folder that documents the test.

**Comment by npetersen2** [comment]
Done in PR #86.
