### ISSUE TITLE
Improve innerNotchedRotor

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/eMach-matlab#97]
Update innerNotchedRotor as follows:

- Remove `alpha_rp` as a parameter from drawing and cross section class
- Add `p` - pole pairs as parameter and describe it on the cross-section drawing
- Add `s` - number of segments to the drawing file 
- Change `One Pole Span` to be `Pole Pitch` and remove italics
- Only math equations should be italicized

**Comment by ngadiyar93** [comment]
Implemented this in PR #98
